name: Build tools
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - name: Set up Node 10.X
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
      id: node
    - name: Install syslibs
      run: sudo apt-get install -y make
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        submodules: 'recursive'
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v1
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}